Portfolio Email Validation
ifeanyi305/portfolio pull request #12
Opened 2022-10-13 13:21 UTC by ifeanyi305

I just validated the input [type="email"] on my portfolio, and I added the following:

- Markup file (HTML) added
- Cascading  stylesheet file added
- Added javascript file
- Html,CSS and JS linters error fixed
- Descriptive readme file added

2022-10-13 13:35 UTC, mckent05 requested changes
Hi @ifeanyi305,

# STATUS: CHANGES REQUIRED ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your code looks clean 👏 
- Your PR title and summary are descriptive 👏 
- All linter checks are passing ✔️ ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 13:35 UTC, mckent05 commented on script.js
> +  }
- According to the project requirement, 'If the validation is not OK, you show an error message to the user near the submit button informing them of the error and the form is not sent'. Your error message is not displayed near the submit button. Please try to fix this 🙏 

Your project:
<img width="792" alt="error" src="https://user-images.githubusercontent.com/73607512/195610985-f6ddb644-b558-4494-ba9c-19c45721f143.PNG">

2022-10-13 15:20 UTC, BertrandConxy approved these changes
Hi @ifeanyi305, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- No linter errors
- project requirements are met
- project works fine
- good PR description
- correct flow is used

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 15:36 UTC, merged

2022-12-17 02:24 UTC, ifeanyi305 commented on script.js
> +  }
Hi, @mckent05 Thanks for the heads up,
I'll change the position for the error message

2022-12-17 02:24 UTC, ifeanyi305 commented
Thank you