Desktop version for portfolio project
ifeanyi305/portfolio pull request #4
Opened 2022-09-29 01:05 UTC by ifeanyi305

I just completed the desktop version for my portfolio and I added the following :

- Added markup file (HTML)
- Added a stylesheet file (CSS)
- Added a gitignore file
- SetUp  HTML, CSS linters
- Added a descriptive Readme file

2022-09-29 01:59 UTC, zieeco requested changes
Hi @ifeanyi305,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 01:59 UTC, zieeco commented on index.html
> +                </ul>
- Please, kindly increase the spacing on the logo and nav items to be close to the design template as much as you can below.

*your design*
![Screenshot from 2022-09-29 02-19-37](https://user-images.githubusercontent.com/59397159/192917586-8c19c880-260e-42a4-8dc9-17d613bd6808.png)


*Figma design*
![Screenshot from 2022-09-29 02-27-47](https://user-images.githubusercontent.com/59397159/192918005-2bcad8a9-6b9f-4bf5-a873-aaee4baf474e.png)

2022-09-29 01:59 UTC, zieeco commented on index.html
> +          <p class="p-tag">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
- Please, kindly adjust your button to the center to match the design as much as you can below

![Screenshot from 2022-09-29 02-20-25](https://user-images.githubusercontent.com/59397159/192918011-daaee2ee-3be4-4233-8a2e-1ac4a834510d.png)

2022-09-29 01:59 UTC, zieeco commented on style.css
> +  .project-container,
- Please, kindly observe the Figma design to reverse **ALL THE CARDS** that were reversed to match the design as much as you can this will help you build the skill of paying attention to details.
![Screenshot from 2022-09-29 02-39-41](https://user-images.githubusercontent.com/59397159/192919624-b8a20ae8-8508-4052-91ac-30e369388841.png)

2022-09-29 01:59 UTC, zieeco commented on index.html
> +          <p class="p-tag">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
- Also, please kindly ensure you've used the correct background image used in the contact form of the desktop version to match the design as much as you can.

2022-09-29 01:59 UTC, zieeco commented on index.html
> +          <p class="p-tag">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
*[OPTIONAL]* kindly add the button interaction to indicate the hover, enabled, disabled and active state to improve the user experience of your webpage.

2022-09-29 01:59 UTC, zieeco commented on index.html
> +          <p class="p-tag">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
*[OPTIONAL]* Kindly remove the border you added to the drop-down button as it's not present in the Figma design to improve your design.

2022-09-29 09:44 UTC, mckent05 approved these changes
Hi @ifeanyi305,

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 09:44 UTC, mckent05 commented on index.html
>                </div>
**OPTIONAL** - There are still some little differences between your design and the figma template. I'd suggest you try to adjust the height of each of your project cards 🙏. Know that replicating the exact specifications gives confidence to recruiters in your ability to design the exact webpage they'll require 👍  

Your design (Please pay attention to the margin between the `see project` button and the bottom margin of the card):
![project card student](https://user-images.githubusercontent.com/73607512/192995703-f090bf7c-c9ba-40d6-8d5a-26664617c45a.PNG)

Figma Template :
![work card student](https://user-images.githubusercontent.com/73607512/192995947-7a0ff460-21b6-4a5f-91b2-1270ae30ad92.PNG)

2022-09-29 09:44 UTC, mckent05 commented on index.html
> +          <p class="p-tag">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
**OPTIONAL** - Good job implementing the changes required by the previous reviewer. I suggest you look into adjusting the width of each of your input fields 🙏, they do not exactly match what is in the Figma template. Remember it is important to replicate the design in the Figma template as close as possible.

Your design:
![contact student now](https://user-images.githubusercontent.com/73607512/192997375-403b900b-ba2c-4f1a-b80e-56f9f7b9cda3.PNG)

Figma design -
![figma desktop contact](https://user-images.githubusercontent.com/73607512/192997479-1de1f50c-b398-4fa7-8752-c723d62356e1.PNG)

2022-09-29 09:44 UTC, mckent05 commented on style.css
> +  .project-container,
**OPTIONAL** - Good job implementing this change suggested by the previous reviewer 👍. Please implement the button interactions such as hover, active,enabled, for all your project buttons 🙏

2022-09-29 10:00 UTC, merged

2022-12-17 02:22 UTC, ifeanyi305 commented on style.css
> +  .project-container,
Hi, @zieeco  thanks for the feedback

2022-12-17 02:22 UTC, ifeanyi305 commented
Thank you